name: Matrix File Creation with Conditional Upload

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-output.outputs.matrix }}
      target: ${{ steps.set-output.outputs.target }}
    steps:
      - name: Set outputs
        id: set-output
        run: |
          echo 'matrix=["iriscommunity20231","iriscommunity20241"]' >> $GITHUB_OUTPUT
          echo 'target="iriscommunity20231"' >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix:
        filename: ${{ fromJson(needs.prepare.outputs.matrix) }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a file
        run: echo "This is a dummy file for ${{ matrix.filename }}" > ${{ matrix.filename }}

      - name: Conditional Upload Artifact
        if: matrix.filename == needs.prepare.outputs.target
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.filename }}
          path: ${{ matrix.filename }}
